version: '3'
services:
  #############
  ## nginx
  #############
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.prod
    image: sagui-nginx
    restart: always
    ports:
      - '80:80'
    links: # Link services to access http://app and  http://api inside the container
      - sagui-api:sagui-api
    depends_on:
      - "sagui-api"
    environment:
      - NODE_ENV=production

  #############
  ## flask api
  #############
  sagui-api:
    build:
      context: ./sagui-api
      dockerfile: Dockerfile.dev
    image: sagui-api
    restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DB_NAME=sagui
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_HOST="mongo"
      - DB_PORT=27017
    links:
      - mongo:mongo
    volumes:
      - ./sagui-api:/app
    ports:
      - '5000'
    depends_on:
      - "mongo"

  #############
  ## mongo
  #############
  mongo:
    image: mongo:4.0.12-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  ###################
  ## mongo web admin
  ###################
  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  ###################
  ## mock data seed
  ###################
  mongo-seed:
    build:
      context: .
      dockerfile: Dockerfile-mongo-seed
    depends_on:
      - "mongo"
    links:
      - mongo

#############
## mongo fix
#############
# volumes:
#   mongo:
