version: '3'
services:
  #############
  ## nginx
  #############
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    image: sagui-nginx
    restart: always
    ports:
      - '80:80'
    links: # Link services to access http://app and  http://api inside the container
      - sagui-api:sagui-api
      - sagui-app:sagui-app
    depends_on:
      - "sagui-api"

  #############
  ## vuejs spa
  #############
  sagui-app:
    build:
      context: ./sagui-app
      dockerfile: Dockerfile.dev
    image: sagui-app
    restart: always
    #environment:
      #- NODE_ENV=development
    volumes: # For webpack dev server to use our local files
      - ./sagui-app:/app
      - /app/node_modules
    ports:
      - '8080:8080' # For docker to now where to redirect HMR queries
    environment:
      - CHOKIDAR_USEPOLLING=true

  #############
  ## flask api
  #############
  sagui-api:
    build:
      context: ./sagui-api
      dockerfile: Dockerfile.dev
    image: sagui-api
    restart: always
    command: "flask run --host=0.0.0.0"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DB_NAME=sagui
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_HOST="mongo"
      - DB_PORT=27017
      #- NODE_ENV=development
    links:
      - mongo:mongo
    volumes:
      - ./sagui-api:/app
    ports:
      - '5000'
    depends_on:
      - "mongo"

  #############
  ## mongo
  #############
  mongo:
    image: mongo:4.0.12-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  ###################
  ## mongo web admin
  ###################
  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

#############
## mongo fix
#############
# volumes:
#   mongo:
